remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lars Spekschoor's homepage
description: This page will mostly be a blog about solutions I found at work.
